### ISSUE TITLE
Unclear text

### ISSUE THREAD

**Issue by justjoheinz** [Gabriella439/Haskell-Lens-Tutorial-Library#13]
At the beginning of the tutorial when the makeLenses "function" is mentioned the documentation says (section _Question: How do I create lenses?_): 

[makeLenses](https://hackage.haskell.org/package/lens-4.17.1/docs/Control-Lens-TH.html#v:makeLenses) creates one lens per field prefixed with an underscore. The lens has the same name as the field without the underscore.

This did irritate me a bit as it was unclear whether the lens is prefixed with the underscore or the field is being prefixed

**Suggestion:**

For each field which is prefixed with an underscore, makeLenses creates one lens. The lens has the same name as the field without the underscore.

**Comment by Gabriella439** [comment]
How does https://github.com/Gabriella439/Haskell-Lens-Tutorial-Library/pull/14 look?
