### ISSUE TITLE
lens type signature is incorrect and order of lambda function is reversed

### ISSUE THREAD

**Issue by waivio** [Gabriella439/Haskell-Lens-Tutorial-Library#7]
I was using the tutorial, it was very helpful, and couldn't understand Lens without it.
I found an error though...
The tutorial says:
lens :: (a -> b) -> (b -> a -> a) -> Lens' a b

If you follow the link for lens the documentation says:
lens :: (s -> a) -> (s -> a -> s) -> Lens' s a

I think the tutorial should be corrected to be:
lens :: (a -> b) -> (a -> b -> a) -> Lens' a b

And likewise the point example should be changed from:
point :: Lens' Atom Point
point = lens _point (\newPoint atom -> atom { _point = newPoint })

To:
point :: Lens' Atom Point
point = lens _point (\atom newPoint -> atom { _point = newPoint })

Thanks,

**Comment by Gabriella439** [comment]
Thank you for pointing that out :)

**Comment by nomeata** [comment]
I was just about to report this. I guess it did not make its way to hackage yet?

**Comment by Gabriella439** [comment]
Thanks for the reminder!  It's up on Hackage now: https://hackage.haskell.org/package/lens-tutorial-1.0.2/docs/Control-Lens-Tutorial.html
