### ISSUE TITLE
How to combine lenses with Haddock?

### ISSUE THREAD

**Issue by pjljvandelaar** [Gabriella439/Haskell-Lens-Tutorial-Library#9]
When I use lenses and haddock I get:

36% (  4 / 11) in 'Const'
 Missing documentation for:
     toBool (src\Const.hs:65)
     toInteger (src\Const.hs:65)
     toText (src\Const.hs:65)
     toXSDRegex (src\Const.hs:65)
     cstrId (src\Const.hs:65)
     args (src\Const.hs:65)
     sort (src\Const.hs:65)

I however could not find in this tutorial how can one add documentation to the getter and setters...

**Comment by Gabriella439** [comment]
@pjljvandelaar: As far as I know there isn't a good way to do this, although you can ask on the `lens` issue tracker just to be sure

**Comment by pjljvandelaar** [comment]
Thanks.

I found https://github.com/ekmett/lens/issues/614.

I will close the issue, since if their is no way you can't include it in your tutorial ;-)

**Comment by Gabriella439** [comment]
You're welcome! 🙂
